site_name: Documentation SAE24
theme:
  name: material
  language: fr
  palette:
 
    - scheme: default
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
      - navigation.tabs
      - navigation.sections
copyright: Copyright &copy; 2021 - 2022 Panchoo Ashvin Padre Maxime Ye Anthony
extra:
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Custom name
    actions:
      - accept
      - manage

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

repo_url: https://github.com/Vito974/SAE24-Front-end
repo_name: ashvin/SAE24-Front-end
